spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_credit_system_application
    username: root
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html